name: Linting
on: workflow_call
permissions: 
  contents: write
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: dependencies
        run: npm ci
      - name: oxlint
        run: | 
            npm run lint > info-lint.md
      - name: Push-changes
        run: |
          git config --global user.name 'tonipekkala24'
          git config --global user.email 'tpekkala24@students.oamk.fi'
          git add .
          git commit -m 'Linting report'
          git push
