name: Module tests
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: dependencies
        run: npm ci
      - name: moduletests
        run: npm test
      - name: test_outcome
        if: ${{success()}}
        run: echo "Test was successfull!!"
