name: Pipeline
on : workflow_dispatch
permissions: 
  contents: write
jobs:
  test:
    uses: './.github/workflows/moduletest.yml'
  lint:
    needs: test
    uses: './.github/workflows/linting.yml'
  build:
    needs: lint
    uses: './.github/workflows/build.yml'
    
